### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by thingdiputra** [FelixNeutatz/2048_M-A-Star#2]
Hello, I don't see a license choice for this repository. I think it's better for you to add license because license is useful to show if whether a user can use your code freely or not. :)

I recommend you to use MIT License because  MIT License is a permissive license that is short and to the point. It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable.

But, you can choose which license you like to use. Check this <a href="http://choosealicense.com/" target="_blank">site!</a>

**Comment by FelixNeutatz** [comment]
Thanks for the recommendation :)
